### PR TITLE
Update material-css-vars.service.ts

### PR DESCRIPTION
**Pull request by javiergacrich**
allow any variable to be updated, not just the one on the MaterialCssVariables list.

### CODE REVIEW

**Comment by johannesjo** [comment]
May I ask why you want to have this change? I am not sure if the benefits (being able to use this as a utility function for setting other css vars?) outweigh the costs (worse autocomplete and no warning when misspelling a variable name).

**Comment by javiergacrich** [comment]
I want to be able to update variables that are not in the MaterialCssVariables list such as _--light-primary-text_ and _--dark-primary-text_

**Comment by johannesjo** [comment]
I'd recommend either using:
```
materialCssVarsService.setVariable('--light-primary-text' as any, 'yourVal')
```
or creating your own dedicated wrapper. At the current point of time, there is also no guarantee that setting your own variables will continue to work (though I've to admit that changing it is pretty unlikely at this point).

**Comment by javiergacrich** [comment]
thanks!

**Pull request closed without merging**
